package initialize

import (
	"jsonrpcmicro/api/router"

	"github.com/gin-gonic/gin"
)

// 初始化总路由

func Routers() *gin.Engine {
	var Router = gin.Default()
	// Router.Use(middleware.LoadTls())  // 打开就能玩https了
	//Router.Use(middleware.Cors()) // 如需跨域可以打开
	// 方便统一添加路由组前缀 多服务器上线使用
	PublicGroup := Router.Group("")
	{
		router.InitAuthRouter(PublicGroup) // 注册基础功能路由 不做鉴权
	}
	// PrivateGroup := Router.Group("")
	// PrivateGroup.Use(middleware.JWTAuth()).Use(middleware.CasbinHandler())
	// {
	// 	router.InitApiRouter(PrivateGroup)                   // 注册功能api路由
	// 	router.InitJwtRouter(PrivateGroup)                   // jwt相关路由
	// 	router.InitUserRouter(PrivateGroup)                  // 注册用户路由
	// 	router.InitMenuRouter(PrivateGroup)                  // 注册menu路由
	// 	router.InitEmailRouter(PrivateGroup)                 // 邮件相关路由
	// 	router.InitSystemRouter(PrivateGroup)                // system相关路由
	// 	router.InitCasbinRouter(PrivateGroup)                // 权限相关路由
	// 	router.InitCustomerRouter(PrivateGroup)              // 客户路由
	// 	router.InitAutoCodeRouter(PrivateGroup)              // 创建自动化代码
	// 	router.InitAuthorityRouter(PrivateGroup)             // 注册角色路由
	// 	router.InitSimpleUploaderRouter(PrivateGroup)        // 断点续传（插件版）
	// 	router.InitSysDictionaryRouter(PrivateGroup)         // 字典管理
	// 	router.InitSysOperationRecordRouter(PrivateGroup)    // 操作记录
	// 	router.InitSysDictionaryDetailRouter(PrivateGroup)   // 字典详情管理
	// 	router.InitFileUploadAndDownloadRouter(PrivateGroup) // 文件上传下载功能路由
	// 	router.InitExcelRouter(PrivateGroup)                 // 表格导入导出
	// 	router.InitMonitorServerRouter(PrivateGroup)         //服务器器监控
	// 	router.InitMonitorWebSSHRouter(PublicGroup)          //webssh连接

	// 	// Code generated by gin-vue-admin Begin; DO NOT EDIT.
	// 	// Code generated by gin-vue-admin End; DO NOT EDIT.
	// }
	return Router
}
